"""regist

Revision ID: 0dbd6ffa1c40
Revises: 9b49345ccd81
Create Date: 2024-10-10 20:33:48.017681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbd6ffa1c40'
down_revision = '9b49345ccd81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.Integer(), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
