"""menu changes

Revision ID: 9b49345ccd81
Revises: 
Create Date: 2024-10-10 19:08:16.463858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b49345ccd81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('date_of_joined', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('password')
    )
    op.create_table('restaurents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.Column('img', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('img', sa.String(length=64), nullable=True),
    sa.Column('rest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rest_id'], ['restaurents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descr'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cartitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartitems')
    op.drop_table('menus')
    op.drop_table('restaurents')
    op.drop_table('profile')
    # ### end Alembic commands ###
